baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
theme = 'github.com/andrew-llcoder/hugo-theme-lexchen'

title = "LexChen Community"

      
[params]
  defaultCover = 'https://raw.githubusercontent.com/lexchen-community/resources/main/bg.png' # default cover image for post not setting cover
  #email = 'floyd.li@outlook.com' # the email address display in the footer
  [[params.socialMedia]] # custom social links display in the footer, you can add one or more
    name = 'Telegram'
    url = 'https://t.me/LexChen_Chat'

  [[params.socialMedia]]
    name = "YouTube"
    url = 'https://www.youtube.com/@LexChenL'
